on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Use my composite action
      uses: mbsaharan/actions-testbed/.github/actions/inputs@v1
      with:
        node-version: '18'